"""Notification adapters and pure message renderers."""

from .telegram_bot import (
    NotificationConfigurationError,
    format_news_message,
    format_signal_message,
    render_news,
    render_news_alert,
    render_incident_alert,
    render_plain_message,
    render_signal,
    render_signal_alert,
    send_message,
    send_incident,
    send_news_alert,
    send_signal,
)
from .whatsapp import (
    WhatsAppDeliveryResult,
    WhatsAppNotifier,
    WhatsAppPayloadError,
    WhatsAppResultCategory,
    render_template_payload as render_whatsapp_template_payload,
    render_text_payload as render_whatsapp_text_payload,
    send_whatsapp_template,
    send_whatsapp_text,
)

__all__ = [
    "NotificationConfigurationError",
    "format_news_message",
    "format_signal_message",
    "render_news",
    "render_news_alert",
    "render_incident_alert",
    "render_plain_message",
    "render_signal",
    "render_signal_alert",
    "send_message",
    "send_incident",
    "send_news_alert",
    "send_signal",
    "WhatsAppDeliveryResult",
    "WhatsAppNotifier",
    "WhatsAppPayloadError",
    "WhatsAppResultCategory",
    "render_whatsapp_template_payload",
    "render_whatsapp_text_payload",
    "send_whatsapp_template",
    "send_whatsapp_text",
]
